name: flutter_mvvm
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  connectivity_plus: ^2.3.6+1
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  dio_cache_interceptor: ^3.3.1
  dio_smart_retry: ^1.3.2
  flash: ^2.0.3+3
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.4
  http: ^0.13.5
  intl: ^0.17.0
  location: ^4.4.0
  retry_bot: ^1.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/
